### Backpropagation in [Pytorch](https://pytorch.org/)

In [16]:
import torch

In [17]:
torch.__version__

'1.7.0+cu101'

In [24]:
lst = [[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]]

In [25]:
input = torch.tensor(lst, requires_grad=True)
input

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], requires_grad=True)

In [27]:
y = input**3 + input**2
y

tensor([[  2.,  12.,  36.],
        [ 80., 150., 252.],
        [392., 576., 810.]], grad_fn=<AddBackward0>)

In [29]:
# Backpropagation

z = y.sum()
z.backward()

In [30]:
input.grad

tensor([[  5.,  16.,  33.],
        [ 56.,  85., 120.],
        [161., 208., 261.]])